grpc:
  server:
    port: 6565
    address: 192.168.1.105
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MiddlewareFactory
    username: postgres
    password: root1234
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        types:
          print:
            banner: false
use-simple: false