openapi: 3.0.3
info:
  title: JsonBodyValidatorData
  description: JsonBodyValidatorData
  version: 1.0.0
paths: {}
components:
  schemas:
    JsonBodyValidatorData:
      type: object
      additionalProperties: false
      properties:
        schema:
          type: object
          additionalProperties:
            type: object
      required:
        - schema

  
